name: Generate Custom GitHub Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *' # run every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch Stats and Save to Folder
        run: |
          mkdir -p .generated

          # Fetch Github Stats
          curl "https://helio-github-stats.vercel.app/api?username=ziad-wdev&theme=radical&hide_border=true&border_radius=16&show_icons=true" -o .generated/github-stats.svg

          # Fetch Streak Stats
          curl "https://github-streak-stats-ruby.vercel.app?user=ziad-wdev&theme=radical&hide_border=true&border_radius=16&short_numbers=true" -o .generated/streak-stats.svg

          # Fetch Top Languages Stats
          curl "https://helio-github-stats.vercel.app/api/top-langs?username=ziad-wdev&theme=radical&hide_border=true&border_radius=16&layout=compact&hide_title=true" -o .generated/top-langs.svg

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .generated/*.svg
          git commit -m "Update GitHub Stats" || exit 0
          git push
